#!/usr/bin/env bash

set -x

while ! (git add . && git commit -m "[sync] source synchronized: $(date '+%Y-%m-%d %H:%M:%S')"); do 
  echo "try again in 30s."; 
  sleep 30
done
while ! (git push); do echo "try again"; done

