#!/usr/bin/env bash

set -x

while (true); do
  while ! (git add . && git commit -m "[sync] source synchronized: $(date '+%Y-%m-%d %H:%M:%S')"); do 
    echo "try again in ${1:-30}."; 
    sleep ${1:-30}
  done
  while ! (git push); do echo "try again"; done
  sleep ${1:-30}
done

