title: 《谍影风云·珍珠港事件》
description: 本书系《谍影风云》之同人续作，主要内容是「关东军特种演习」和「珍珠港事件」两个主线内容。此外，还会将主角脱甲这条线串联在连个主线内容当中。
author: Jiaqi Yang
github: https://github.com/NingZhiheng
about:
disqus_shortname:
google_analytics:

enableTags: true
tagarray: []

collections:
  project:
    output: false
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/NingZhiheng"

share:
  twitter_username:
  fb_appid:

urls:
    - text: 关于
      url: /about/
    - text: XML Feed
      url: /feed.xml

url: "https://ningzhiheng.github.io/the-novel-pearl-harbor"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
